'use client';
import React from "react";
import './globals.css'
import {Inter} from 'next/font/google'
import {Container} from "@nextui-org/react";

const inter = Inter({subsets: ['latin']})


export default function RootLayout({children,}: { children: React.ReactNode }) {
    const metadata = {
        title: 'Create Next App',
        description: 'Generated by create next app',
    }

    return (
        <html lang="en">
        <body className={inter.className}>
        <Container>
            {children}
        </Container>

        </body>
        </html>
    )
}
