import {Expense} from "@/lib/Interfaces";

export const fakeData: any[] | Expense[] = [
    {
        "id": "expense_001",
        "amount": 50.25,
        "categoryID": "Groceries_1",
        "description": "Groceries",
        "is_yearly": false,
        "is_monthly": true,
        "month": 7,
        "name": "Monthly Grocery Expense",
        "date": "2023-07-15T12:34:56",
        "year": 2023
    },
    {
        "id": "expense_002",
        "amount": 1200.00,
        "categoryID": "Housing_2",
        "description": "Rent",
        "is_yearly": false,
        "is_monthly": true,
        "month": 7,
        "name": "Monthly Rent",
        "date": "2023-07-01T00:00:00",
        "year": 2023
    },
    {
        "id": "expense_003",
        "amount": 250.00,
        "categoryID": "Housing_003",
        "description": "Internet Bill",
        "is_yearly": false,
        "is_monthly": true,
        "month": 7,
        "name": "Monthly Internet Expense",
        "date": "2023-07-10T18:30:00",
        "year": 2023
    },
    {
        "id": "expense_004",
        "amount": 1200.00,
        "categoryID": "Housing_3",
        "description": "Car Insurance",
        "is_yearly": true,
        "is_monthly": false,
        "month": 1,
        "name": "Yearly Car Insurance",
        "date": "2023-01-05T09:00:00",
        "year": 2023
    },
    {
        "id": "expense_005",
        "amount": 80.00,
        "categoryID": "Personal_1",
        "description": "Gym Membership",
        "is_yearly": true,
        "is_monthly": false,
        "month": 1,
        "name": "Yearly Gym Membership",
        "date": "2023-01-01T08:00:00",
        "year": 2023
    },
    {
        "id": "expense_006",
        "amount": 35.75,
        "categoryID": "Groceries_2",
        "description": "Weekly Grocery Expense",
        "is_yearly": false,
        "is_monthly": false,
        "month": 8,
        "name": "Weekly Groceries",
        "date": "2023-08-05T14:45:00",
        "year": 2023
    },
    {
        "id": "expense_007",
        "amount": 450.00,
        "categoryID": "Housing_4",
        "description": "Electricity Bill",
        "is_yearly": false,
        "is_monthly": true,
        "month": 8,
        "name": "Monthly Electricity Expense",
        "date": "2023-08-15T20:00:00",
        "year": 2023
    },
    {
        "id": "expense_008",
        "amount": 40.00,
        "categoryID": "Entertainment_1",
        "description": "Movie Night",
        "is_yearly": false,
        "is_monthly": false,
        "month": 8,
        "name": "Movie Night Expense",
        "date": "2023-08-10T19:30:00",
        "year": 2023
    },
    {
        "id": "expense_009",
        "amount": 150.00,
        "categoryID": "Transportation_1",
        "description": "Public Transit Pass",
        "is_yearly": false,
        "is_monthly": true,
        "month": 8,
        "name": "Monthly Transit Pass",
        "date": "2023-08-01T08:00:00",
        "year": 2023
    },
    {
        "id": "expense_010",
        "amount": 500.00,
        "categoryID": "Shopping_1",
        "description": "Clothing Shopping",
        "is_yearly": false,
        "is_monthly": false,
        "month": 8,
        "name": "Clothing Shopping Expense",
        "date": "2023-08-20T15:15:00",
        "year": 2023
    },
    {
        "id": "expense_011",
        "amount": 75.00,
        "categoryID": "Groceries_3",
        "description": "Snack Supplies",
        "is_yearly": false,
        "is_monthly": false,
        "month": 9,
        "name": "Monthly Snacks",
        "date": "2023-09-05T10:00:00",
        "year": 2023
    },
    {
        "id": "expense_012",
        "amount": 950.00,
        "categoryID": "Housing_5",
        "description": "Mortgage Payment",
        "is_yearly": false,
        "is_monthly": true,
        "month": 9,
        "name": "Monthly Mortgage",
        "date": "2023-09-01T12:00:00",
        "year": 2023
    },
    {
        "id": "expense_013",
        "amount": 25.00,
        "categoryID": "Entertainment_2",
        "description": "Game Subscription",
        "is_yearly": false,
        "is_monthly": true,
        "month": 9,
        "name": "Monthly Game Subscription",
        "date": "2023-09-10T16:30:00",
        "year": 2023
    },
    {
        "id": "expense_014",
        "amount": 80.00,
        "categoryID": "Transportation_2",
        "description": "Fuel",
        "is_yearly": false,
        "is_monthly": true,
        "month": 9,
        "name": "Monthly Fuel Expense",
        "date": "2023-09-20T09:45:00",
        "year": 2023
    },
    {
        "id": "expense_015",
        "amount": 200.00,
        "categoryID": "Shopping_2",
        "description": "Electronics Purchase",
        "is_yearly": false,
        "is_monthly": false,
        "month": 9,
        "name": "Electronics Shopping",
        "date": "2023-09-15T14:00:00",
        "year": 2023
    },
    {
        "id": "expense_016",
        "amount": 100.00,
        "categoryID": "Groceries_4",
        "description": "Farmers Market",
        "is_yearly": false,
        "is_monthly": false,
        "month": 10,
        "name": "Farmers Market Expense",
        "date": "2023-10-05T11:30:00",
        "year": 2023
    },
    {
        "id": "expense_017",
        "amount": 800.00,
        "categoryID": "Housing_6",
        "description": "Property Taxes",
        "is_yearly": true,
        "is_monthly": false,
        "month": 10,
        "name": "Yearly Property Taxes",
        "date": "2023-10-15T08:00:00",
        "year": 2023
    },
    {
        "id": "expense_018",
        "amount": 60.00,
        "categoryID": "Entertainment_3",
        "description": "Concert Tickets",
        "is_yearly": false,
        "is_monthly": false,
        "month": 10,
        "name": "Concert Expense",
        "date": "2023-10-10T19:00:00",
        "year": 2023
    },
    {
        "id": "expense_019",
        "amount": 200.00,
        "categoryID": "Transportation_3",
        "description": "Car Maintenance",
        "is_yearly": false,
        "is_monthly": false,
        "month": 10,
        "name": "Car Maintenance Expense",
        "date": "2023-10-25T10:00:00",
        "year": 2023
    },
    {
        "id": "expense_020",
        "amount": 200.00,
        "categoryID": "Personal_2",
        "description": "Spa Day",
        "is_yearly": false,
        "is_monthly": false,
        "month": 9,
        "name": "Spa Day Expense",
        "date": "2023-09-12T11:00:00",
        "year": 2023
    }
];
